/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedTabbedRouteImport } from './routes/_authenticated/_tabbed'
import { Route as AuthenticatedTabbedIndexRouteImport } from './routes/_authenticated/_tabbed/index'
import { Route as AuthenticatedTabbedSettingsRouteImport } from './routes/_authenticated/_tabbed/settings'
import { Route as AuthenticatedTabbedAiSyncRouteImport } from './routes/_authenticated/_tabbed/ai-sync'
import { Route as AuthenticatedTabbedAddTransactionRouteImport } from './routes/_authenticated/_tabbed/add-transaction'
import { Route as AuthenticatedTabbedActivityRouteImport } from './routes/_authenticated/_tabbed/activity'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTabbedRoute = AuthenticatedTabbedRouteImport.update({
  id: '/_tabbed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTabbedIndexRoute =
  AuthenticatedTabbedIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTabbedRoute,
  } as any)
const AuthenticatedTabbedSettingsRoute =
  AuthenticatedTabbedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedTabbedRoute,
  } as any)
const AuthenticatedTabbedAiSyncRoute =
  AuthenticatedTabbedAiSyncRouteImport.update({
    id: '/ai-sync',
    path: '/ai-sync',
    getParentRoute: () => AuthenticatedTabbedRoute,
  } as any)
const AuthenticatedTabbedAddTransactionRoute =
  AuthenticatedTabbedAddTransactionRouteImport.update({
    id: '/add-transaction',
    path: '/add-transaction',
    getParentRoute: () => AuthenticatedTabbedRoute,
  } as any)
const AuthenticatedTabbedActivityRoute =
  AuthenticatedTabbedActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedTabbedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedTabbedIndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedTabbedActivityRoute
  '/add-transaction': typeof AuthenticatedTabbedAddTransactionRoute
  '/ai-sync': typeof AuthenticatedTabbedAiSyncRoute
  '/settings': typeof AuthenticatedTabbedSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedTabbedIndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/activity': typeof AuthenticatedTabbedActivityRoute
  '/add-transaction': typeof AuthenticatedTabbedAddTransactionRoute
  '/ai-sync': typeof AuthenticatedTabbedAiSyncRoute
  '/settings': typeof AuthenticatedTabbedSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/_tabbed': typeof AuthenticatedTabbedRouteWithChildren
  '/_authenticated/_tabbed/activity': typeof AuthenticatedTabbedActivityRoute
  '/_authenticated/_tabbed/add-transaction': typeof AuthenticatedTabbedAddTransactionRoute
  '/_authenticated/_tabbed/ai-sync': typeof AuthenticatedTabbedAiSyncRoute
  '/_authenticated/_tabbed/settings': typeof AuthenticatedTabbedSettingsRoute
  '/_authenticated/_tabbed/': typeof AuthenticatedTabbedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/activity'
    | '/add-transaction'
    | '/ai-sync'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/activity'
    | '/add-transaction'
    | '/ai-sync'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_authenticated/_tabbed'
    | '/_authenticated/_tabbed/activity'
    | '/_authenticated/_tabbed/add-transaction'
    | '/_authenticated/_tabbed/ai-sync'
    | '/_authenticated/_tabbed/settings'
    | '/_authenticated/_tabbed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_tabbed': {
      id: '/_authenticated/_tabbed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedTabbedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_tabbed/': {
      id: '/_authenticated/_tabbed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedTabbedIndexRouteImport
      parentRoute: typeof AuthenticatedTabbedRoute
    }
    '/_authenticated/_tabbed/settings': {
      id: '/_authenticated/_tabbed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedTabbedSettingsRouteImport
      parentRoute: typeof AuthenticatedTabbedRoute
    }
    '/_authenticated/_tabbed/ai-sync': {
      id: '/_authenticated/_tabbed/ai-sync'
      path: '/ai-sync'
      fullPath: '/ai-sync'
      preLoaderRoute: typeof AuthenticatedTabbedAiSyncRouteImport
      parentRoute: typeof AuthenticatedTabbedRoute
    }
    '/_authenticated/_tabbed/add-transaction': {
      id: '/_authenticated/_tabbed/add-transaction'
      path: '/add-transaction'
      fullPath: '/add-transaction'
      preLoaderRoute: typeof AuthenticatedTabbedAddTransactionRouteImport
      parentRoute: typeof AuthenticatedTabbedRoute
    }
    '/_authenticated/_tabbed/activity': {
      id: '/_authenticated/_tabbed/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedTabbedActivityRouteImport
      parentRoute: typeof AuthenticatedTabbedRoute
    }
  }
}

interface AuthenticatedTabbedRouteChildren {
  AuthenticatedTabbedActivityRoute: typeof AuthenticatedTabbedActivityRoute
  AuthenticatedTabbedAddTransactionRoute: typeof AuthenticatedTabbedAddTransactionRoute
  AuthenticatedTabbedAiSyncRoute: typeof AuthenticatedTabbedAiSyncRoute
  AuthenticatedTabbedSettingsRoute: typeof AuthenticatedTabbedSettingsRoute
  AuthenticatedTabbedIndexRoute: typeof AuthenticatedTabbedIndexRoute
}

const AuthenticatedTabbedRouteChildren: AuthenticatedTabbedRouteChildren = {
  AuthenticatedTabbedActivityRoute: AuthenticatedTabbedActivityRoute,
  AuthenticatedTabbedAddTransactionRoute:
    AuthenticatedTabbedAddTransactionRoute,
  AuthenticatedTabbedAiSyncRoute: AuthenticatedTabbedAiSyncRoute,
  AuthenticatedTabbedSettingsRoute: AuthenticatedTabbedSettingsRoute,
  AuthenticatedTabbedIndexRoute: AuthenticatedTabbedIndexRoute,
}

const AuthenticatedTabbedRouteWithChildren =
  AuthenticatedTabbedRoute._addFileChildren(AuthenticatedTabbedRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedTabbedRoute: typeof AuthenticatedTabbedRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTabbedRoute: AuthenticatedTabbedRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
